<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>EMZ Clothing Shop</title>
    <style>
        body {
            background-color: #121212;
            color: #ffffff;
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
        }
        header {
            background-color: #1f1f1f;
            padding: 20px;
            text-align: center;
        }
        header h1 {
            margin: 0;
            font-size: 2.5em;
        }
        nav {
            text-align: center;
            padding: 10px;
            background-color: #333333;
        }
        nav a {
            color: #ffffff;
            margin: 0 15px;
            text-decoration: none;
            font-size: 1.2em;
        }
        .content {
            padding: 20px;
        }
        .product {
            background-color: #1f1f1f;
            border-radius: 5px;
            padding: 15px;
            margin: 10px 0;
        }
        .product img {
            max-width: 100%;
            border-radius: 5px;
        }
        .product h2 {
            margin: 10px 0 5px 0;
        }
        .product p {
            margin: 0 0 10px 0;
        }
        footer {
            text-align: center;
            padding: 20px;
            background-color: #1f1f1f;
            position: fixed;
            width: 100%;
            bottom: 0;
        }
    </style>
</head>
<body>
    <header>
        <h1>EMZ Clothing Shop</h1>
        <p>David Zakinov</p>
    </header>
    <nav>
        <a href="#">Home</a>
        <a href="#">About</a>
        <a href="#">Shop</a>
        <a href="#">Contact</a>
    </nav>
    <div class="content">
        <h2>Featured Products</h2>
        <div class="product">
            <img src="https://via.placeholder.com/300" alt="Product 1">
            <h2>Product 1</h2>
            <p>Description of Product 1</p>
            <p>Price: $29.99</p>
        </div>
        <div class="product">
            <img src="https://via.placeholder.com/300" alt="Product 2">
            <h2>Product 2</h2>
            <p>Description of Product 2</p>
            <p>Price: $39.99</p>
        </div>
    </div>
    <footer>
        <p>&copy; 2024 EMZ Clothing Shop</p>
    </footer>
</body>
</html>

